#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall: 
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: ubuntu22
    password: $6$0s1HLA7YnBDAiQQi$r7/jG9GkRGDB4PhFLNRkU01WoJpXw/hSKIk3BNDnNVCgyG6wDGrhf4kb.NPHPO5X3XrBPwLkY6aDMs72hQPjy0
    realname: user
    username: user
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      all-nics:
        match:
          name: e*
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-server
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    config:
    - ptable: gpt
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: true
      id: disk-sda
      type: disk
    - ptable: gpt
      path: /dev/sdb
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: false
      id: disk-sdb
      type: disk
    - device: disk-sda
      size: 1048576
      flag: bios_grub
      number: 1
      preserve: false
      grub_device: false
      offset: 1048576
      id: partition-0
      type: partition
    - device: disk-sda
      size: 1073741824
      wipe: superblock
      number: 2
      preserve: false
      grub_device: false
      offset: 2097152
      id: partition-1
      type: partition
    - device: disk-sda
      size: 2147483648
      wipe: superblock
      number: 3
      preserve: false
      grub_device: false
      offset: 1075838976
      id: partition-2
      type: partition
    - device: disk-sda
      size: 30064771072
      wipe: superblock
      number: 4
      preserve: false
      grub_device: false
      offset: 3223322624
      id: partition-3
      type: partition
    - device: disk-sdb
      size: 1073741824
      wipe: superblock
      number: 1
      preserve: false
      grub_device: false
      offset: 1048576
      id: partition-4
      type: partition
    - device: disk-sdb
      size: 2147483648
      wipe: superblock
      number: 2
      preserve: false
      grub_device: false
      offset: 1074790400
      id: partition-5
      type: partition
    - device: disk-sdb
      size: 30064771072
      wipe: superblock
      number: 3
      preserve: false
      grub_device: false
      offset: 3222274048
      id: partition-6
      type: partition
    - name: md/boot
      raidlevel: raid1
      devices:
      - partition-1
      - partition-4
      spare_devices: []
      preserve: false
      wipe: superblock-recursive
      ptable: gpt
      id: raid-0
      type: raid
    - name: md/swap
      raidlevel: raid1
      devices:
      - partition-2
      - partition-5
      spare_devices: []
      preserve: false
      wipe: superblock-recursive
      ptable: gpt
      id: raid-1
      type: raid
    - name: md/root
      raidlevel: raid1
      devices:
      - partition-3
      - partition-6
      spare_devices: []
      preserve: false
      wipe: superblock-recursive
      ptable: gpt
      id: raid-2
      type: raid
    - device: raid-0
      size: 1069547520
      wipe: superblock
      number: 1
      preserve: false
      grub_device: false
      offset: 1048576
      id: partition-7
      type: partition
    - fstype: ext4
      volume: partition-7
      preserve: false
      id: format-0
      type: format
    - device: raid-1
      size: 2142240768
      wipe: superblock
      flag: swap
      number: 1
      preserve: false
      grub_device: false
      offset: 1048576
      id: partition-8
      type: partition
    - fstype: swap
      volume: partition-8
      preserve: false
      id: format-1
      type: format
    - path: ''
      device: format-1
      id: mount-1
      type: mount
    - device: raid-2
      size: 30044848128
      wipe: superblock
      number: 1
      preserve: false
      grub_device: false
      offset: 1048576
      id: partition-9
      type: partition
    - fstype: ext4
      volume: partition-9
      preserve: false
      id: format-2
      type: format
    - path: /
      device: format-2
      id: mount-2
      type: mount
    - path: /boot
      device: format-0
      id: mount-0
      type: mount
    swap:
      size: 0
  updates: security
  version: 1

